install:
	sudo pacman -S ice-ssb
clean:
	sudo pacman -R ice-ssb
symlink:
	sudo ln -s ~/.dotfiles/ice/applications ~/.local/share/
	sudo ln -s ~/.dotfiles/ice/ice ~/.local/share/
symlink_clean:
	rm -rf ~/.local/share/ice
	rm -rf ~/.local/share/applications
