#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#3b4252"
bspc config active_border_color "#8fbcbb"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#d08770"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# replace caps with control
setxkbmap -option ctrl:nocaps

# screenkey
screenkey --mods-only --start-disabled --mouse --font-size small --opacity 0.5 --font-color "#eceff4" --bg-color "#434c5e"
