install:
	sudo pacman -S bspwm

clean:
	sudo pacman -R bspwm

update:
	sudo pacman -U bswm

symlink:
	mkdir ~/.config; mkdir ~/.config/bspwm
	ln -s ~/.dotfiles/bspwm/bspwmrc ~/.config/bspwm/bspwmrc

symlink_clean:
	rm -rf ~/.config/bspwm
