source "${HOME}/.zsh/functions.zsh"
eval "$(starship init zsh)"

add_plugin "Aloxaf/fzf-tab"
add_plugin "zsh-users/zsh-syntax-highlighting"

add_file "autocomplete.zsh"
add_file "fzf.zsh"
add_file "alias.zsh"
